name: CI

on: [push]

jobs:
  build:
    name: Code quality
    runs-on: ubuntu-latest
    container: python:3.8
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check with flake8
        run: |
          pip install flake8
          flake8 --max-line-length=88 .
      
      - name: Check with isort
        run: |
          pip install isort
          isort --check .
